version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:5000'
    depends_on:
      - postgres
    env_file:
      - app/.env
    volumes:
      - file-store:/app/store


volumes:
  postgres-data:
  file-store: